nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"

packageExtensions:
  nodemon-webpack-plugin@*:
    peerDependenciesMeta:
      webpack:
        optional: true

yarnPath: .yarn/releases/yarn-4.17.1.cjs
